[theme]
base = "light"
primaryColor = "#4F46E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
